# -*- coding: utf-8 -*-
"""MCP Threat Scanner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W50kwiStDfpfFsqOc5ZK3X0Lm-tN7UPN
"""

#!/usr/bin/env python3
"""
MCP Threat Scanner (Agentic Threat Radar)
Author: Nicolas Ray | Founder, Fortis Intelligence
Target Environment: AWS Lambda / GitHub Actions

Description:
A static analysis tool designed to scan Model Context Protocol (MCP) server
repositories for critical security misconfigurations, focusing on risks introduced
by LLM tool execution (RCE, NeighborJack bypasses, and Auth token leakage).

Rulesets mapped to recent MCP CVEs (e.g., CVE-2025-53107, CVE-2025-6514).
"""

import os
import re
import json
import logging
from dataclasses import dataclass, asdict
from typing import List, Dict, Any

# Configure Professional Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - [%(levelname)s] - %(message)s'
)
logger = logging.getLogger("MCPThreatScanner")

@dataclass
class ThreatVulnerability:
    severity: str        # CRITICAL, HIGH, MEDIUM, LOW
    category: str        # RCE, Network, Auth, SupplyChain
    title: str
    description: str
    file_path: str
    line_number: int

@dataclass
class MCPServerReport:
    repo_name: str
    risk_score: int      # 0 (Safe) to 100 (Critical)
    vulnerabilities: List[ThreatVulnerability]
    scanned_files: int

class MCPSecurityAnalyzer:
    """Core analysis engine for detecting MCP-specific threat vectors."""

    # Signatures mapped to known MCP attack vectors
    THREAT_SIGNATURES = {
        "RCE": [
            (r"child_process\.exec\(", "Node.js OS Command Injection Risk (CVE-2025-53107)"),
            (r"subprocess\.Popen\([^)]*shell=True", "Python Arbitrary Shell Execution"),
            (r"os\.system\(", "Python OS System Call"),
            (r"eval\(", "Unsafe Eval Execution")
        ],
        "Network": [
            (r"0\.0\.0\.0", "NeighborJack Vulnerability (Exposed Localhost Binding)"),
            (r"app\.listen\([^)]*['\"]0\.0\.0\.0['\"]", "Unrestricted MCP Server Binding")
        ],
        "Auth": [
            (r"process\.env\.[A-Z_]*TOKEN", "Hardcoded or Env-based Static Tokens (Missing OAuth 2.1)"),
            (r"api_key\s*=\s*['\"][A-Za-z0-9_-]+['\"]", "Plaintext API Key in Source")
        ]
    }

    def __init__(self, target_dir: str):
        self.target_dir = target_dir
        self.scanned_files = 0
        self.findings: List[ThreatVulnerability] = []

    def scan_file(self, filepath: str):
        """Scans a single file against all threat signatures."""
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                lines = f.readlines()

            for line_idx, line in enumerate(lines):
                # Check RCE
                for pattern, title in self.THREAT_SIGNATURES["RCE"]:
                    if re.search(pattern, line):
                        self._add_finding("CRITICAL", "RCE", title, "Unsanitized command execution allows LLM to hijack host shell.", filepath, line_idx + 1)

                # Check Network
                for pattern, title in self.THREAT_SIGNATURES["Network"]:
                    if re.search(pattern, line):
                        self._add_finding("HIGH", "Network", title, "Binding to 0.0.0.0 exposes the MCP server to local network hijacking.", filepath, line_idx + 1)

                # Check Auth
                for pattern, title in self.THREAT_SIGNATURES["Auth"]:
                    if re.search(pattern, line):
                        self._add_finding("MEDIUM", "Auth", title, "Use of static credentials instead of OAuth 2.1 / PKCE.", filepath, line_idx + 1)

            self.scanned_files += 1
        except Exception as e:
            logger.warning(f"Could not read {filepath}: {e}")

    def _add_finding(self, severity: str, category: str, title: str, desc: str, path: str, line: int):
        vuln = ThreatVulnerability(severity, category, title, desc, path, line)
        self.findings.append(vuln)

    def calculate_risk_score(self) -> int:
        """Calculates a normalized 0-100 risk score based on finding severity."""
        score = 0
        for f in self.findings:
            if f.severity == "CRITICAL": score += 35
            elif f.severity == "HIGH": score += 20
            elif f.severity == "MEDIUM": score += 10
        return min(100, score)

    def run_analysis(self, repo_name: str) -> MCPServerReport:
        """Executes the full directory scan and generates the report."""
        logger.info(f"Initiating Agentic Threat Scan on repository: {repo_name}")

        for root, _, files in os.walk(self.target_dir):
            for file in files:
                if file.endswith(('.js', '.ts', '.py', '.json', '.yml')):
                    self.scan_file(os.path.join(root, file))

        score = self.calculate_risk_score()
        logger.info(f"Scan complete. Risk Score: {score}/100. Vulnerabilities: {len(self.findings)}")

        return MCPServerReport(
            repo_name=repo_name,
            risk_score=score,
            vulnerabilities=self.findings,
            scanned_files=self.scanned_files
        )

def export_to_json(reports: List[MCPServerReport], output_path: str):
    """Exports the security reports to a JSON file for the front-end dashboard."""
    payload = {
        "last_updated": "2026-05-01T12:00:00Z",
        "total_scanned": len(reports),
        "data": [asdict(r) for r in reports]
    }
    with open(output_path, 'w') as f:
        json.dump(payload, f, indent=4)
    logger.info(f"Exported threat intelligence to {output_path}")

if __name__ == "__main__":
    # --- Example Execution for GitHub Actions ---
    # In production, this would iterate over cloned repos from your MCP catalog

    # Mocking a scan on a hypothetical vulnerable directory
    scanner = MCPSecurityAnalyzer(target_dir="./")

    # We will manually inject mock data to demonstrate the output structure
    mock_report = MCPServerReport(
        repo_name="cyanheads/git-mcp-server",
        risk_score=95,
        scanned_files=142,
        vulnerabilities=[
            ThreatVulnerability("CRITICAL", "RCE", "Node.js OS Command Injection Risk", "child_process.exec found. Allows indirect prompt injection to execute OS commands.", "src/git.ts", 45),
            ThreatVulnerability("HIGH", "Network", "NeighborJack Vulnerability", "Server bound to 0.0.0.0 without authentication.", "src/index.ts", 12)
        ]
    )

    mock_report_2 = MCPServerReport(
        repo_name="anthropic/sqlite-mcp-demo",
        risk_score=45,
        scanned_files=38,
        vulnerabilities=[
            ThreatVulnerability("MEDIUM", "Auth", "Static API Token Usage", "Found static tokens in env instead of OAuth 2.1 compliance.", "config.py", 18)
        ]
    )

    export_to_json([mock_report, mock_report_2], "threat_data.json")